
LTO_ENABLE			= yes
CONSOLE_ENABLE		= no
COMMAND_ENABLE		= no
GRAVE_ESC_ENABLE	= no
MAGIC_ENABLE		= no

OLED_ENABLE			= yes
OLED_DRIVER			= SSD1306
ENCODER_ENABLE		= yes
EXTRAKEY_ENABLE		= yes
MOUSEKEY_ENABLE		= yes
WPM_ENABLE			= yes
VIA_ENABLE			= no
DEBOUNCE_TYPE		= asym_eager_defer_pk
